"""empty message

Revision ID: 4dc49ed11afa
Revises: f8a5072d21da
Create Date: 2022-10-28 19:03:35.231239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc49ed11afa'
down_revision = 'f8a5072d21da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'sobre_mi',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('usuarios', 'preferencias',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('usuarios', 'url_avatar',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'url_avatar',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('usuarios', 'preferencias',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('usuarios', 'sobre_mi',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
