"""empty message

Revision ID: 81aabb8b0f52
Revises: a23ae26a1257
Create Date: 2022-10-27 19:22:55.171514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81aabb8b0f52'
down_revision = 'a23ae26a1257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('modelo', sa.String(length=250), nullable=False),
    sa.Column('kms_por_litro', sa.Integer(), nullable=False),
    sa.Column('cantidad_asientos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
