"""empty message

Revision ID: f8a5072d21da
Revises: d971fd8f8a2f
Create Date: 2022-10-28 18:59:17.163028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a5072d21da'
down_revision = 'd971fd8f8a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre_usuario', sa.String(length=250), nullable=False))
    op.drop_column('usuarios', 'usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('usuario', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'nombre_usuario')
    # ### end Alembic commands ###
