"""empty message

Revision ID: f96dcaf161fb
Revises: 81aabb8b0f52
Create Date: 2022-10-27 19:32:58.060743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96dcaf161fb'
down_revision = '81aabb8b0f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acerca', sa.String(length=250), nullable=False),
    sa.Column('conductor', sa.Integer(), nullable=True),
    sa.Column('vehiculo', sa.Integer(), nullable=True),
    sa.Column('desde', sa.String(length=250), nullable=False),
    sa.Column('hasta', sa.String(length=250), nullable=False),
    sa.Column('fecha', sa.Integer(), nullable=False),
    sa.Column('hora', sa.Integer(), nullable=False),
    sa.Column('asientos_disponibles', sa.Integer(), nullable=False),
    sa.Column('costo_asiento_uy', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conductor'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viajes')
    # ### end Alembic commands ###
